version: "2.4"
services:
  mysql:
    container_name: mysql
    image: mariadb/server:10.3
    volumes:
      - ./sql-data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    hostname: localhost
    environment:
      MYSQL_DATABASE: 'megadigitaltest'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'mysqlpassword'
      MYSQL_ROOT_PASSWORD: 'mysqlpassword'
      MYSQL_ROOT_PASSWORD: 'mysqlpassword'